### PR TITLE
Display user blogs in MyAccount/Chiturca/issue86

### LINKED ISSUE #86: Read user's blogs from fire base and show them in user account page
## Summary

fetch user blogs from fire base

### Screenshots

image

### Constriant

- [ ] do it with redux toolkit

### PR DESCRIPTION
**Pull request by chiturca**
# Description

For displaying user blogs into MyAccount component:

- BlogsSlice.js has been added and related function for firebase has been added, but right now it just get info on my userID because I could not added user id info into the function yet, but you can see related blogs into the console.
- GetBlogs.jsx has been added, I am still working on the rendering and displaying the data.
- There are some changes in the firebase blogs collection parallel to the changes on WriteBlog.

- userID has been added to WriteBlog in order to make a filter based on userID so that display of the specified user info can be shown on the page.
- date and likes have been added to WriteBlog in order to take that info from firebase and add it later to blogs page.

- Navbar fixes has been added we talked about before.
- UserNavbar has been deleted from the project since it is useless.

Since there is no display right now, I will not add any images for now.
I suggest we should split the work on this issue because it is huge.

Lastly, these changes gives no error on my part, but just in case, first review it in VS Code so it will not be a problem for later ✌️   

## Related Issue

-  Fixes #86

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Tested locally
- [ ] Added tests

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes
- [x] I've run linter, prettier, and removed all `console.log`
- [ ] I've reverted all the files back that are not related to the issue (App.js, index.js, ...)

### CODE REVIEW

**Comment by chiturca** [comment]
userblogs

- Thanks to help coming from #95 this part is done.
- I just changed BlogCard into MyAccountCard because in blogs page the contents when user is not writing anything will be different between blogs page and user page.

- Please first of all review and approve his page because some conflicts will be occur. After I solve them in here we can merge this one too.
- Thanks all for coorporation ✌️

**Comment by chiturca** [comment]
rounded

Conflicts has been solved and profile photos made rounded.

**Review by Omer-Amr — APPROVED** [review]
Looks Amazing thanks for your efforts

**Review by batoulst — APPROVED** [review]
thank u @chiturca

**Pull request merged**
