### PR TITLE
Navbar styling and login for sm --Chiturca/issue139

### LINKED ISSUE #139: Fix navbar style
User navbar "Home" needs to be "Blogs" to prevent complications with footer. 
BG color can be transparent so that it fits to every page color
Navbar should be stick to website and should be accessible when user scroll down

Image

### PR DESCRIPTION
**Pull request by chiturca**
# Description

lg screen:

- bg made transparent
- signin option implemented
- for logged in user, photo added
- onClick photo dropdown menu added(navigate to myaccountdetails and sign out)

sm screen:

- bg colored
- signup/signin options added
- for logged in user, photo added
- onClick photo dropdown menu added(navigate to myaccountdetails and sign out)

## Related Issue

- Fixes #139 

## Screenshots
Ekran Görüntüsü (6)

Ekran Görüntüsü (8)
Ekran Görüntüsü (9)
Ekran Görüntüsü (10)
Ekran Görüntüsü (11)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- [x] Tested locally
- [ ] Added tests

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes
- [x] I've run linter, prettier, and removed all `console.log`
- [x] I've reverted all the files back that are not related to the issue (App.js, index.js, ...)

### CODE REVIEW

**Review by Omer-Amr — APPROVED** [review]
Looks very good! thank you

**Review by ladycodeer — COMMENTED** [review]
Thank you Miray, everything looks good, but the "or sign in" option part doesn't look good actually, can we change it?

**Comment by chiturca** [comment]
> Thank you Miray, everything looks good, but the "or sign in" option part doesn't look good actually, can we change it?

Yep, I will erase it 🤗

**Comment by chiturca** [comment]
For lg, bg shadow added and "or sign in" part deleted and sign-up button changed into sign-in as we talked before.
For sm, requested animation has been implemented fyi 👍 

image

**Review by ahmadmhd357 — APPROVED** [review]
amazing thank you so much

**Pull request merged**
