### PR TITLE
Ahmadmhd357/issue36

### LINKED ISSUE #36: Blog-page
---
Name: New Feature 💡
About: Adding the blog page to the website.
labels: enhancement
---

## Summary

start designing the blog page with react and tailwind css.

### Screenshots

Image

### Constraints / Details
Good luck.

### PR DESCRIPTION
**Pull request by ahmadmhd357**
# Description

created and styled both blogs and a single blog page
because these pages depend on data I used temporary data for testing
so you can consider this as temporary work just to see the pages and understand the flow of data between them

## Related Issue

Fixes #36 

## Screenshots
Screenshot (26)
Screenshot (28)
Screenshot (29)
Screenshot (30)
Screenshot (31)
Screenshot (22)
Screenshot (23)
Screenshot (24)
Screenshot (25)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [x] Tested locally

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes
- [x] I've run linter, prettier, and removed all `console.log`
- [x] I've reverted all the files back that are not related to the issue (App.js, index.js, ...)

### CODE REVIEW

**Comment by chiturca** [comment]
I admire your work, looking good and also I liked slick carousel, thanks for this info!

For future reviewer(s);

npm installation:
npm install react-slick --save

**Review by chiturca — APPROVED** [review]
I admire your work, looking good and also I liked slick carousel, thanks for this info!

For future reviewer(s);

npm installation:
npm install react-slick --save

**Comment by ahmadmhd357** [comment]
> I admire your work, looking good and also I liked slick carousel, thanks for this info!
> 
> For future reviewer(s);
> 
> npm installation: npm install react-slick --save

thank you so much,
for the library yes I liked it so much and I'm thinking about applying this to all the sliders on the website

**Review by batoulst — APPROVED** [review]
good work Ahmad

**Pull request merged**
